In [3]:
#------------------------------Import Libraries-----------------------
#------------------------------Set Color & Theme----------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
# Suppress warning messages for clean notebook execution
warnings.filterwarnings('ignore')

NAVY = '#1F3864'
AMBER = '#E8A33D'
PALETTE = [NAVY, AMBER, '#5B7DB1', '#F2C572', '#8FA6C9', '#C97F1E']

sns.set_theme(style='whitegrid')
plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.edgecolor'] = '#333333'
plt.rcParams['font.size'] = 10

In [4]:
#-------------------------Data Load From Excel----------------------------
#-------------------------659,318 Rows Import Across All 9 Tables---------

Customers = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\customers.csv"
df1 = pd.read_csv(Customers)
print(df1)

Products = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\products.csv"
df2 = pd.read_csv(Products)
print(df2)

Marketing_Campaigns = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\marketing_campaigns.csv"
df3 = pd.read_csv(Marketing_Campaigns)
print(df3)

Orders = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\orders.csv"
df4 = pd.read_csv(Orders)
print(df4)

Order_items = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\order_items.csv"
df5 = pd.read_csv(Order_items)
print(df5)

Payments = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\payments.csv"
df6 = pd.read_csv(Payments)
print(df6)

Returns = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\returns.csv"
df7 = pd.read_csv(Returns)
print(df7)

Shipments = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\shipments.csv"
df8 = pd.read_csv(Shipments)
print(df8)

Customer_reviews = r"E:\Indian E-Commerce Sales & Customer Analytics\Excel Files\customer_reviews.csv"
df9 = pd.read_csv(Customer_reviews)
print(df9)

      customer_id customer_signup_date  gender   age age_group  \
0      CUST100000           2023-01-09    Male  44.0     35-44
1      CUST100001           2023-04-10    Male  20.0     18-24
2      CUST100002           2025-05-09  Female  35.0     35-44
3      CUST100003           2024-12-24  Female  34.0     25-34
4      CUST100004           2023-08-15    Male  38.0     35-44
...           ...                  ...     ...   ...       ...
24995  CUST124995           2024-03-02    Male  33.0     25-34
24996  CUST124996           2023-06-19  Female  52.0     45-54
24997  CUST124997           2025-11-01    Male  18.0     18-24
24998  CUST124998           2025-02-01    Male  35.0     35-44
24999  CUST124999           2025-11-23  Female  51.0     45-54

                state           city  pincode_prefix customer_segment  \
0      Madhya Pradesh         Indore             607          Regular
1         West Bengal        Kolkata             245          Regular
2             Gujarat      Ahmedabad             160          Premium
3         Maharashtra           Pune             175              New
4      Andhra Pradesh  Visakhapatnam             446           Budget
...               ...            ...             ...              ...
24995      Tamil Nadu     Coimbatore             740              New
24996         Haryana      Faridabad             762          Premium
24997          Punjab       Ludhiana             668          Regular
24998   Uttar Pradesh         Kanpur             636              New
24999     West Bengal        Kolkata             348           Budget

      preferred_device preferred_payment_method       acquisition_channel  \
0           Mobile App                      EMI                 Affiliate
1           Mobile App         Cash on Delivery            Organic Search
2           Mobile Web                      UPI             SMS Marketing
3           Mobile App                      UPI      Influencer Marketing
4              Desktop         Cash on Delivery                  Referral
...                ...                      ...                       ...
24995       Mobile App                      UPI      Influencer Marketing
24996       Mobile App         Cash on Delivery  Social Media - Instagram
24997       Mobile App                      UPI            Organic Search
24998       Mobile App         Cash on Delivery   Social Media - Facebook
24999       Mobile Web                      UPI               Paid Search

       total_orders  total_spend last_order_date  average_order_value  \
0                 3     36884.57      2023-05-26             12294.86
1                 7    371585.73      2024-05-23             53083.68
2                10    114901.74      2025-07-14             11490.17
3                 1      3788.82      2025-12-19              3788.82
4                 2     61295.90      2023-11-01             30647.95
...             ...          ...             ...                  ...
24995             0         0.00             NaN                 0.00
24996            12    248614.37      2024-06-23             20717.86
24997             4    197907.83      2025-12-12             49476.96
24998             0         0.00             NaN                 0.00
24999             2     10526.56      2025-12-19              5263.28

       customer_status loyalty_tier
0              Churned       Bronze
1              Churned         Gold
2              At Risk       Silver
3               Active       Bronze
4              Churned       Silver
...                ...          ...
24995  Never Purchased       Bronze
24996          Churned         Gold
24997           Active         Gold
24998  Never Purchased       Bronze
24999           Active       Bronze

[25000 rows x 18 columns]
    product_id                              product_name            category  \
0    PROD10000                          Sen Basic Staple             Grocery
1    PROD10001  Gupta-Chandra Essential Men's Bottomwear             Fashion
2    PROD10002            Murty, Advanced Women's Casual            Footwear
3    PROD10003             Madan-Kanda Signature Bedding      Home & Kitchen
4    PROD10004                  Sami, Premium Home Decor      Home & Kitchen
..         ...                                       ...                 ...
545  PROD10545                    Ray Classic Phone Case  Mobile Accessories
546  PROD10546                 Wali-Nadig Compact Staple             Grocery
547  PROD10547              Mody-Kari Signature Ayurveda   Health & Wellness
548  PROD10548                 Chanda Everyday Kids Wear             Fashion
549  PROD10549              Sunder, Smart Medical Device   Health & Wellness

          subcategory          brand   price  cost_price discount_range  \
0             Staples            Sen   220.0      173.88          0-15%
1    Men's Bottomwear  Gupta-Chandra  4060.0     2375.50         10-25%
2      Women's Casual         Murty,  2800.0     1740.98         25-40%
3             Bedding    Madan-Kanda  5680.0     4330.67         15-30%
4          Home Decor          Sami,   370.0      250.98         25-40%
..                ...            ...     ...         ...            ...
545       Phone Cases            Ray   500.0      333.08         30-45%
546           Staples     Wali-Nadig   470.0      380.52          5-20%
547          Ayurveda      Mody-Kari  1210.0      887.73         20-35%
548         Kids Wear         Chanda   700.0      431.96         20-35%
549   Medical Devices        Sunder,   860.0      625.00         25-40%

     rating_average  rating_count  stock_quantity product_launch_date  \
0               4.4            32            1422          2025-12-12
1               5.0            13            1595          2023-09-01
2               4.2           139             732          2024-12-24
3               4.1            31            1181          2024-03-28
4               4.5           279            2597          2024-02-03
..              ...           ...             ...                 ...
545             4.7            11            1095          2024-08-08
546             4.7            22            2230          2023-10-26
547             3.9            26              28          2025-01-06
548             4.5           163            2985          2025-07-09
549             4.0           125             231          2023-12-16

    product_type  return_rate_baseline
0        Premium                0.0118
1         Budget                0.1678
2        Premium                0.2193
3        Premium                0.0689
4       Standard                0.0664
..           ...                   ...
545     Standard                0.0700
546       Budget                0.0104
547     Standard                0.0349
548     Standard                0.2242
549     Standard                0.0382

[550 rows x 14 columns]
    campaign_id                                     campaign_name  \
0      CAMP1001              Direct/App Festival Special Jan 2023
1      CAMP1002      Social Media - Instagram Flash Sale Jan 2023
2      CAMP1003        Organic Search New Product Launch Jan 2023
3      CAMP1004           SMS Marketing Festival Special Jan 2023
4      CAMP1005       Email Marketing New Product Launch Feb 2023
..          ...                                               ...
146    CAMP1147  Social Media - Facebook Loyalty Program Dec 2025
147    CAMP1148                Referral Festival Special Dec 2025
148    CAMP1149                SMS Marketing Retargeting Dec 2025
149    CAMP1150          Email Marketing Brand Awareness Dec 2025
150    CAMP1151           Organic Search Loyalty Program Dec 2025

                      channel campaign_start_date campaign_end_date  \
0                  Direct/App          2023-01-06        2023-01-23
1    Social Media - Instagram          2023-01-02        2023-01-11
2              Organic Search          2023-01-03        2023-01-18
3               SMS Marketing          2023-01-01        2023-01-11
4             Email Marketing          2023-02-02        2023-02-19
..                        ...                 ...               ...
146   Social Media - Facebook          2025-12-05        2025-12-20
147                  Referral          2025-12-02        2025-12-13
148             SMS Marketing          2025-12-02        2025-12-12
149           Email Marketing          2025-12-05        2025-12-18
150            Organic Search          2025-12-08        2025-12-20

          campaign_type target_segment  discount_percentage  conversions  \
0    New Product Launch        Premium                   20           27
1       Loyalty Program        Premium                   25           10
2         Seasonal Sale        Regular                   30           40
3      Festival Special            All                   25            2
4       Loyalty Program         Budget                   15           43
..                  ...            ...                  ...          ...
146     Loyalty Program         Budget                   25          304
147     Brand Awareness        Regular                   15          154
148     Brand Awareness         Budget                   15           90
149    Festival Special         Budget                   20          277
150         Retargeting         Budget                    5          700

     revenue_generated  impressions  clicks  campaign_cost    roi
0            698500.58          606     166       97919.42  6.133
1            262727.62        18769     359       83998.79  2.128
2           1640037.86         2155     452      418495.64  2.919
3             11607.02          296      30       13777.19 -0.158
4            991507.43         2480     393      163106.97  5.079
..                 ...          ...     ...            ...    ...
146         7090181.16       642631   11791     3212313.51  1.207
147         3548942.62         2940     775      669508.11  4.301
148         1760634.09        13385    1275      789582.13  1.230
149         5538352.37        15237    2361      979471.76  4.654
150        19254691.73        39916    7452     3117122.03  5.177

[151 rows x 14 columns]
         order_id customer_id  order_date order_time order_status  \
0      ORD1000000  CUST103868  2025-08-16   22:35:23       Failed
1      ORD1000001  CUST118472  2023-02-11   18:51:17    Delivered
2      ORD1000002  CUST120793  2024-12-14   11:08:38    Delivered
3      ORD1000003  CUST109166  2025-11-23   09:32:24       Failed
4      ORD1000004  CUST119895  2025-07-27   20:35:25    Cancelled
...           ...         ...         ...        ...          ...
99995  ORD1099995  CUST120257  2025-12-28   20:16:02   Processing
99996  ORD1099996  CUST107829  2024-09-02   14:27:56    Delivered
99997  ORD1099997  CUST108115  2024-04-22   20:44:15    Delivered
99998  ORD1099998  CUST109794  2024-10-27   22:37:35    Delivered
99999  ORD1099999  CUST118669  2025-12-15   15:38:19    Delivered

       shipping_method       delivery_city delivery_state coupon_code  \
0             Next-Day              Mumbai    Maharashtra      FEST20
1      Economy/Surface  Thiruvananthapuram         Kerala      FEST20
2      Economy/Surface              Nagpur    Maharashtra        APP5
3              Express               Kochi         Kerala  BIGBILLION
4             Standard              Jaipur      Rajasthan      SAVE15
...                ...                 ...            ...         ...
99995         Next-Day              Nagpur    Maharashtra      FLAT50
99996  Economy/Surface            Vadodara        Gujarat      FEST20
99997         Next-Day            Vadodara        Gujarat    FREESHIP
99998         Standard            Vadodara        Gujarat         NaN
99999         Standard                Pune    Maharashtra      FEST20

       discount_percentage         marketing_channel   subtotal  shipping_fee  \
0                      5.0             SMS Marketing   14439.90           0.0
1                     15.0   Social Media - Facebook    4760.00           0.0
2                     30.0  Social Media - Instagram     826.00           0.0
3                      5.0                Direct/App   25878.00           0.0
4                     30.0            Organic Search    3450.00           0.0
...                    ...                       ...        ...           ...
99995                 10.0   Social Media - Facebook   12142.35           0.0
99996                 15.0            Organic Search   21615.00           0.0
99997                 25.0   Social Media - Facebook    3957.60           0.0
99998                 20.0           Email Marketing   10518.70           0.0
99999                 15.0                Direct/App  226997.00           0.0

       tax_amount  final_amount campaign_id
0          722.00      15161.90         NaN
1          238.00       4998.00    CAMP1008
2           41.30        867.30    CAMP1101
3         1293.90      27171.90         NaN
4          172.50       3622.50         NaN
...           ...           ...         ...
99995      607.12      12749.47         NaN
99996     1080.75      22695.75         NaN
99997      197.88       4155.48         NaN
99998      525.94      11044.64         NaN
99999    11349.85     238346.85         NaN

[100000 rows x 16 columns]
       order_item_id    order_id product_id  quantity  unit_price  \
0         OI10000000  ORD1000000  PROD10347         4       150.0
1         OI10000001  ORD1000000  PROD10510         1      1150.0
2         OI10000002  ORD1000000  PROD10305         2       960.0
3         OI10000003  ORD1000000  PROD10092         4       920.0
4         OI10000004  ORD1000000  PROD10417         3      2640.0
...              ...         ...        ...       ...         ...
254326    OI10254326  ORD1099998  PROD10510         1      1150.0
254327    OI10254327  ORD1099998  PROD10365         3       360.0
254328    OI10254328  ORD1099998  PROD10392         1      8430.0
254329    OI10254329  ORD1099999  PROD10484         3      4060.0
254330    OI10254330  ORD1099999  PROD10246         4     66050.0

        discount_percentage  item_revenue  item_cost    profit
0                       6.5        561.00     515.92     45.08
1                       5.0       1092.50     752.18    340.32
2                       8.0       1766.40    1217.66    548.74
3                       5.0       3496.00    3049.52    446.48
4                       5.0       7524.00    6847.65    676.35
...                     ...           ...        ...       ...
254326                 20.0        920.00     752.18    167.82
254327                 20.0        864.00     731.79    132.21
254328                 21.5       6617.55    5840.02    777.53
254329                 15.0      10353.00   10325.49     27.51
254330                 18.0     216644.00  226671.32 -10027.32

[254331 rows x 9 columns]
       payment_id    order_id payment_date    payment_method payment_status  \
0      PAY1000000  ORD1000000   2025-08-16               EMI         Failed
1      PAY1000001  ORD1000001   2023-02-12               UPI        Success
2      PAY1000002  ORD1000002   2024-12-14       Net Banking        Success
3      PAY1000003  ORD1000003   2025-11-23  Cash on Delivery    Not Charged
4      PAY1000004  ORD1000004   2025-07-27  Cash on Delivery    Not Charged
...           ...         ...          ...               ...            ...
99995  PAY1099995  ORD1099995   2025-12-29       Net Banking        Success
99996  PAY1099996  ORD1099996   2024-09-02  Cash on Delivery        Success
99997  PAY1099997  ORD1099997   2024-04-23        Debit Card        Success
99998  PAY1099998  ORD1099998   2024-10-27               UPI        Success
99999  PAY1099999  ORD1099999   2025-12-15       Credit Card        Success

       amount_paid  transaction_fee  refund_amount
0             0.00              0.0            0.0
1          4998.00              0.0            0.0
2           867.30              0.0            0.0
3             0.00              0.0            0.0
4             0.00              0.0            0.0
...            ...              ...            ...
99995     12749.47              0.0            0.0
99996     22695.75              0.0            0.0
99997      4155.48              0.0            0.0
99998     11044.64              0.0            0.0
99999    238346.85           3575.2            0.0

[100000 rows x 8 columns]
       return_id    order_id customer_id product_id return_date  \
0      RET100000  ORD1000009  CUST117396  PROD10073  2024-05-28
1      RET100001  ORD1000019  CUST122124  PROD10077  2023-12-30
2      RET100002  ORD1000019  CUST122124  PROD10451  2024-01-06
3      RET100003  ORD1000019  CUST122124  PROD10043  2024-01-05
4      RET100004  ORD1000028  CUST101962  PROD10171  2023-06-19
...          ...         ...         ...        ...         ...
12070  RET112070  ORD1099916  CUST114201  PROD10328  2025-12-17
12071  RET112071  ORD1099948  CUST113856  PROD10376  2023-05-25
12072  RET112072  ORD1099971  CUST108197  PROD10205  2023-08-21
12073  RET112073  ORD1099975  CUST123174  PROD10035  2025-10-23
12074  RET112074  ORD1099980  CUST123614  PROD10482  2024-12-28

                 return_reason  refund_amount     return_status
0                 Changed mind        2094.40  Refund Completed
1              Product damaged        1040.00  Refund Completed
2                Wrong product           0.00           Pending
3                Quality issue       15104.00  Refund Completed
4                 Changed mind           0.00           Pending
...                        ...            ...               ...
12070            Late delivery       31338.75  Refund Completed
12071               Size issue       16636.65  Refund Completed
12072  Product not as expected           0.00           Pending
12073          Product damaged        4396.00  Refund Completed
12074  Product not as expected         140.00  Refund Completed

[12075 rows x 8 columns]
       shipment_id    order_id        warehouse_city       delivery_city  \
0      SHIP1000000  ORD1000001               Chennai  Thiruvananthapuram
1      SHIP1000001  ORD1000002                Mumbai              Nagpur
2      SHIP1000002  ORD1000005               Chennai          Coimbatore
3      SHIP1000003  ORD1000006  Delhi-NCR (Gurugram)               Noida
4      SHIP1000004  ORD1000007               Chennai  Thiruvananthapuram
...            ...         ...                   ...                 ...
89676  SHIP1089676  ORD1099994               Kolkata               Patna
89677  SHIP1089677  ORD1099996             Ahmedabad            Vadodara
89678  SHIP1089678  ORD1099997             Ahmedabad            Vadodara
89679  SHIP1089679  ORD1099998             Ahmedabad            Vadodara
89680  SHIP1089680  ORD1099999                Mumbai                Pune

       shipping_method dispatch_date expected_delivery_date  \
0      Economy/Surface    2023-02-11             2023-02-19
1      Economy/Surface    2024-12-15             2024-12-23
2             Standard    2025-01-09             2025-01-13
3             Same-Day    2025-05-26             2025-05-26
4              Express    2025-10-04             2025-10-06
...                ...           ...                    ...
89676  Economy/Surface    2025-03-26             2025-04-03
89677  Economy/Surface    2024-09-03             2024-09-11
89678         Next-Day    2024-04-23             2024-04-25
89679         Standard    2024-10-27             2024-10-31
89680         Standard    2025-12-15             2025-12-19

      actual_delivery_date  delivery_days       delivery_status  delayed_flag
0               2023-02-17            6.0             Delivered             0
1               2024-12-26           11.0             Delivered             1
2               2025-01-12            3.0             Delivered             0

In [22]:
#--------------Data Overview & Quality Check---------------
tables_df = {
    'Customers' : df1,
    'Products' : df2,
    'Marketing_Campaigns' : df3,
    'Orders' : df4,
    'Order_items' : df5,
    'Payments' : df6,
    'Returns' : df7,
    'Shipments' : df8,
    'Customer_reviews' : df9
}

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77530 entries, 0 to 77529
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   review_id          77530 non-null  object
 1   order_id           77530 non-null  object
 2   customer_id        77530 non-null  object
 3   product_id         77530 non-null  object
 4   review_date        77530 non-null  object
 5   rating             77530 non-null  int64
 6   review_sentiment   77297 non-null  object
 7   verified_purchase  77530 non-null  bool
dtypes: bool(1), int64(1), object(6)
memory usage: 4.2+ MB

In [24]:
df.describe()

             rating
count  77530.000000
mean       3.691939
std        0.904587
min        1.000000
25%        3.000000
50%        4.000000
75%        4.000000
max        5.000000

In [25]:
df.head()

,review_id,order_id,customer_id,product_id,review_date,rating,review_sentiment,verified_purchase
0,REV100000,ORD1000002,CUST120793,PROD10470,2024-12-30,4,Positive,True
1,REV100001,ORD1000005,CUST123408,PROD10085,2025-02-04,4,Positive,True
2,REV100002,ORD1000005,CUST123408,PROD10233,2025-01-27,5,Positive,True
3,REV100003,ORD1000006,CUST117355,PROD10176,2025-06-11,4,Positive,True
4,REV100004,ORD1000006,CUST117355,PROD10210,2025-06-06,3,Neutral,True

In [8]:
#------------------1. Shape, missing values, duplicates summary--------------
overview = pd.DataFrame({
    'rows': {k: len(v) for k, v in tables_df.items()},
    'columns': {k: v.shape[1] for k, v in tables_df.items()},
    'missing_values': {k: v.isnull().sum().sum() for k, v in tables_df.items()},
    'duplicate_rows': {k: v.duplicated().sum() for k, v in tables_df.items()}
})
print(overview.sort_values('rows', ascending=False))
print(f"\nTotal rows across all files: {sum(len(t) for t in tables_df.values()):,}")

                       rows  columns  missing_values  duplicate_rows
Order_items          254331        9               0               0
Payments             100000        8               0               0
Orders               100000       16          116532               0
Shipments             89681       11            4642               0
Customer_reviews      77530        8             233               0
Customers             25000       18            2675               0
Returns               12075        8               0               0
Products                550       14               4               0
Marketing_Campaigns     151       14               0               0

Total rows across all files: 659,318

In [18]:
# 2. Data types per table
for name, df in tables_df.items():
    print(f"\n--- {name} dtypes ---")
    print(df.dtypes)

# 3. Missing values breakdown (only columns with nulls)
print("=== MISSING VALUES BY COLUMN ===")
for name, df in tables_df.items():
    nulls = df.isnull().sum()
    nulls = nulls[nulls > 0]
    if len(nulls):
        print(f"\n--- {name} ---")
        print(nulls)
        print(f"% missing: {(nulls / len(df) * 100).round(2).to_dict()}")

--- Customers dtypes ---
customer_id                  object
customer_signup_date         object
gender                       object
age                         float64
age_group                    object
state                        object
city                         object
pincode_prefix                int64
customer_segment             object
preferred_device             object
preferred_payment_method     object
acquisition_channel          object
total_orders                  int64
total_spend                 float64
last_order_date              object
average_order_value         float64
customer_status              object
loyalty_tier                 object
dtype: object

--- Products dtypes ---
product_id               object
product_name             object
category                 object
subcategory              object
brand                    object
price                   float64
cost_price              float64
discount_range           object
rating_average          float64
rating_count              int64
stock_quantity            int64
product_launch_date      object
product_type             object
return_rate_baseline    float64
dtype: object

--- Marketing_Campaigns dtypes ---
campaign_id             object
campaign_name           object
channel                 object
campaign_start_date     object
campaign_end_date       object
campaign_type           object
target_segment          object
discount_percentage      int64
conversions              int64
revenue_generated      float64
impressions              int64
clicks                   int64
campaign_cost          float64
roi                    float64
dtype: object

--- Orders dtypes ---
order_id                object
customer_id             object
order_date              object
order_time              object
order_status            object
shipping_method         object
delivery_city           object
delivery_state          object
coupon_code             object
discount_percentage    float64
marketing_channel       object
subtotal               float64
shipping_fee           float64
tax_amount             float64
final_amount           float64
campaign_id             object
dtype: object

--- Order_items dtypes ---
order_item_id           object
order_id                object
product_id              object
quantity                 int64
unit_price             float64
discount_percentage    float64
item_revenue           float64
item_cost              float64
profit                 float64
dtype: object

--- Payments dtypes ---
payment_id          object
order_id            object
payment_date        object
payment_method      object
payment_status      object
amount_paid        float64
transaction_fee    float64
refund_amount      float64
dtype: object

--- Returns dtypes ---
return_id         object
order_id          object
customer_id       object
product_id        object
return_date       object
return_reason     object
refund_amount    float64
return_status     object
dtype: object

--- Shipments dtypes ---
shipment_id                object
order_id                   object
warehouse_city             object
delivery_city              object
shipping_method            object
dispatch_date              object
expected_delivery_date     object
actual_delivery_date       object
delivery_days             float64
delivery_status            object
delayed_flag                int64
dtype: object

--- Customer_reviews dtypes ---
review_id            object
order_id             object
customer_id          object
product_id           object
review_date          object
rating                int64
review_sentiment     object
verified_purchase      bool
dtype: object
=== MISSING VALUES BY COLUMN ===

--- Customers ---
age                  250
preferred_device     125
last_order_date     2300
dtype: int64
% missing: {'age': 1.0, 'preferred_device': 0.5, 'last_order_date': 9.2}

--- Products ---
rating_average    4
dtype: int64
% missing: {'rating_average': 0.73}

--- Orders ---
coupon_code    33711
campaign_id    82821
dtype: int64
% missing: {'coupon_code': 33.71, 'campaign_id': 82.82}

--- Shipments ---
actual_delivery_date    2321
delivery_days           2321
dtype: int64
% missing: {'actual_delivery_date': 2.59, 'delivery_days': 2.59}

--- Customer_reviews ---
review_sentiment    233
dtype: int64
% missing: {'review_sentiment': 0.3}

In [30]:
valid_orders = Orders[Orders['order_status'] != 'Failed'].copy()
valid_orders['year_month'] = valid_orders['order_date'].dt.to_period('M').astype(str)

monthly = valid_orders.groupby('year_month').agg(
    revenue=('final_amount', 'sum'),
    orders=('order_id', 'count')
).reset_index()

fig, ax1 = plt.subplots(figsize=(13, 5))
ax1.bar(monthly['year_month'], monthly['revenue'], color=NAVY, alpha=0.85, label='Revenue')
ax1.set_ylabel('Revenue (₹)', color=NAVY)
ax1.tick_params(axis='x', rotation=90)
ax2 = ax1.twinx()
ax2.plot(monthly['year_month'], monthly['orders'], color=AMBER, marker='o', linewidth=2, label='Orders')
ax2.set_ylabel('Order Count', color=AMBER)
plt.title('Monthly Revenue & Order Volume', fontsize=13, color=NAVY, fontweight='bold')
fig.tight_layout()
plt.show()

TypeError: string indices must be integers, not 'str'